# Generated by Django 6.0.7 on 2026-07-26 13:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author",
            name="email",
        ),
        migrations.AddField(
            model_name="author",
            name="email_address",
            field=models.EmailField(default="", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="blog.author",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="tag",
            field=models.ManyToManyField(to="blog.tag"),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(
                validators=[django.core.validators.MinLengthValidator(10)]
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="excerpt",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="post",
            name="image_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(default="", unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="tag",
            name="caption",
            field=models.CharField(max_length=20),
        ),
    ]
